# Generated by Django 6.0.3 on 2026-04-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_active_household_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
