# Generated by Django 6.0.3 on 2026-04-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '사용자 (User)', 'verbose_name_plural': '사용자 목록 (Users)'},
        ),
        migrations.AlterModelOptions(
            name='historicalcustomuser',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 사용자 (User)', 'verbose_name_plural': 'historical 사용자 목록 (Users)'},
        ),
    ]
