# Generated by Django 6.0.3 on 2026-04-01 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 식비, 월급, 보험료', max_length=50)),
                ('type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10)),
                ('is_fixed', models.BooleanField(default=False, help_text='지출일 경우 고정비(True)인지 변동비(False)인지 구분합니다.', verbose_name='고정비 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='ledgers.household')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, help_text='상세 분류', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledgers.category'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 신용카드, 카카오페이, 현금', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='ledgers.household')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='결제수단', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ledgers.paymentmethod'),
        ),
    ]
