# Generated by Django 6.0.3 on 2026-04-01 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_category_transaction_category_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='payment_day',
            field=models.IntegerField(blank=True, help_text='고정 지출일 또는 급여(수입) 수령일 (1~31). 대시보드 기본 조회 기간 산출에 사용됩니다.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='지출/수령 일자'),
        ),
    ]
