# Generated by Django 6.0.3 on 2026-04-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_category_payment_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fixed_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='고정비의 월 예정 지출 금액 (원). 고정비 카테고리에만 입력하세요.', max_digits=12, null=True, verbose_name='고정 금액'),
        ),
    ]
