# Generated by Django 6.0.3 on 2026-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0004_category_fixed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='end_date',
            field=models.DateField(blank=True, help_text='고정비 종료일자. 비워두면 무기한 지출로 간주합니다.', null=True, verbose_name='종료일자'),
        ),
        migrations.AddField(
            model_name='category',
            name='start_date',
            field=models.DateField(blank=True, help_text='고정비 시작일자. 이 날짜부터 대시보드에 예정 검이 표시됩니다.', null=True, verbose_name='시작일자'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='삭제 요청 시 True로 표시 (실제 DB에서 제거하지 않음 - 소프트 삭제).', verbose_name='삭제 여부'),
        ),
    ]
