# Generated by Django 6.0.3 on 2026-04-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_category_end_date_category_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', '수입'), ('expense', '지출'), ('savings', '저금')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', '수입'), ('expense', '지출'), ('savings', '저금')], default='expense', max_length=10),
        ),
    ]
