# Generated by Django 6.0.3 on 2026-04-07 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_alter_category_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', '수입'), ('expense', '지출'), ('transfer', '이체/저축')], default='expense', max_length=10),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='예: 농협 월급통장, 신한카드, 청약통장', max_length=50)),
                ('asset_type', models.CharField(choices=[('cash', '현금'), ('bank', '입출금 통장'), ('savings', '저축/적금'), ('card', '신용/체크카드')], default='bank', max_length=20, verbose_name='자산 유형')),
                ('initial_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='초기 잔액')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ledgers.household')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_asset',
            field=models.ForeignKey(blank=True, help_text='돈이 들어온 통장', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposits', to='ledgers.asset'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_asset',
            field=models.ForeignKey(blank=True, help_text='돈이 빠져나간 통장/카드', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdraws', to='ledgers.asset'),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
