# Generated by Django 6.0.3 on 2026-04-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0007_remove_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', '수입'), ('expense', '지출'), ('savings_deposit', '저축 넣기(입금)'), ('savings_withdraw', '저축 깨기(출금)'), ('transfer', '단순 이체')], default='expense', max_length=20),
        ),
    ]
