# Generated by Django 6.0.3 on 2026-04-30 00:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0008_alter_transaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHousehold',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('household_type', models.CharField(choices=[('personal', '개인'), ('group', '그룹')], default='personal', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('admin_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical household',
                'verbose_name_plural': 'historical households',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, help_text='거래 금액 (원)', max_digits=12)),
                ('date', models.DateField(help_text='거래 날짜')),
                ('description', models.CharField(help_text='내역 내용', max_length=255)),
                ('transaction_type', models.CharField(choices=[('income', '수입'), ('expense', '지출'), ('savings_deposit', '저축 넣기(입금)'), ('savings_withdraw', '저축 깨기(출금)'), ('transfer', '단순 이체')], default='expense', max_length=20)),
                ('image', models.TextField(blank=True, help_text='영수증 이미지', max_length=100, null=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='삭제 요청 시 True로 표시 (실제 DB에서 제거하지 않음 - 소프트 삭제).', verbose_name='삭제 여부')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='상세 분류', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledgers.category')),
                ('deposit_asset', models.ForeignKey(blank=True, db_constraint=False, help_text='돈이 들어온 통장', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledgers.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledgers.household')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('withdraw_asset', models.ForeignKey(blank=True, db_constraint=False, help_text='돈이 빠져나간 통장/카드', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ledgers.asset')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
