# Generated by Django 6.0.3 on 2026-04-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0009_historicalhousehold_historicaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='계좌번호/카드번호'),
        ),
        migrations.AddField(
            model_name='asset',
            name='bank_name',
            field=models.CharField(blank=True, help_text='예: 농협, 신한카드', max_length=50, null=True, verbose_name='은행/카드사명'),
        ),
    ]
