# Generated by Django 6.0.3 on 2026-04-30 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_asset_account_number_asset_bank_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'verbose_name': '자산 (Asset)', 'verbose_name_plural': '자산 목록 (Assets)'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '분류 (Category)', 'verbose_name_plural': '분류 목록 (Categories)'},
        ),
        migrations.AlterModelOptions(
            name='historicalhousehold',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 가계부 (Household)', 'verbose_name_plural': 'historical 가계부 목록 (Households)'},
        ),
        migrations.AlterModelOptions(
            name='historicaltransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 거래 내역 (Transaction)', 'verbose_name_plural': 'historical 거래 내역 목록 (Transactions)'},
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'verbose_name': '가계부 (Household)', 'verbose_name_plural': '가계부 목록 (Households)'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': '거래 내역 (Transaction)', 'verbose_name_plural': '거래 내역 목록 (Transactions)'},
        ),
    ]
