# Generated by Django 6.0.3 on 2026-04-30 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0011_alter_asset_options_alter_category_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='중복되지 않는 고유한 그룹 이름을 입력하세요.', max_length=100, unique=True, verbose_name='그룹 이름')),
                ('description', models.TextField(help_text='이 그룹의 목적이나 설명을 자유롭게 작성해주세요.', verbose_name='설명(Memo)')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('approved', '승인됨'), ('rejected', '거절됨')], default='pending', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 일시')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_requests', to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': '그룹 생성 요청 (Group Request)',
                'verbose_name_plural': '그룹 생성 요청 목록 (Group Requests)',
                'ordering': ['-created_at'],
            },
        ),
    ]
