# Generated by Django 6.0.3 on 2026-04-30 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0012_grouprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequest',
            name='requested_members',
            field=models.ManyToManyField(blank=True, help_text='이 그룹에 포함할 멤버들을 선택하세요.', related_name='group_invites', to=settings.AUTH_USER_MODEL, verbose_name='포함할 멤버'),
        ),
    ]
