# Generated by Django 6.0.3 on 2026-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0013_grouprequest_requested_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='memo',
            field=models.TextField(blank=True, help_text='이 자산에 대한 간략한 메모나 코멘트를 자유롭게 작성해주세요.', null=True, verbose_name='메모'),
        ),
    ]
