# Generated by Django 6.0.3 on 2026-05-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0014_asset_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('cash', '현금'), ('bank', '입출금 통장'), ('savings', '저축/적금'), ('card', '신용/체크카드'), ('pay', '포인트/페이'), ('investment', '투자/주식/코인'), ('loan', '대출/부채'), ('insurance', '보험')], default='bank', max_length=20, verbose_name='자산 유형'),
        ),
    ]
