# Generated by Django 6.0.3 on 2026-05-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0015_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='merchant',
            field=models.CharField(blank=True, help_text='사용처 (선택)', max_length=100, null=True, verbose_name='사용처'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='merchant',
            field=models.CharField(blank=True, help_text='사용처 (선택)', max_length=100, null=True, verbose_name='사용처'),
        ),
    ]
