# Generated by Django 6.0.3 on 2026-05-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0016_historicaltransaction_merchant_transaction_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalhousehold',
            name='default_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='기본 조회 시작일'),
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='default_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='기본 조회 종료일'),
        ),
        migrations.AddField(
            model_name='household',
            name='default_date_from',
            field=models.DateField(blank=True, null=True, verbose_name='기본 조회 시작일'),
        ),
        migrations.AddField(
            model_name='household',
            name='default_date_to',
            field=models.DateField(blank=True, null=True, verbose_name='기본 조회 종료일'),
        ),
    ]
