# Generated by Django 6.0.3 on 2026-05-13 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0017_historicalhousehold_default_date_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='default_date_from',
        ),
        migrations.RemoveField(
            model_name='historicalhousehold',
            name='default_date_to',
        ),
        migrations.RemoveField(
            model_name='household',
            name='default_date_from',
        ),
        migrations.RemoveField(
            model_name='household',
            name='default_date_to',
        ),
        migrations.AddField(
            model_name='historicalhousehold',
            name='budget_start_day',
            field=models.IntegerField(blank=True, help_text='매월 이 날짜를 가계부 주기의 시작일로 설정합니다. (예: 1이면 1일~말일, 25이면 25일~24일)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='가계부 주기 시작일'),
        ),
        migrations.AddField(
            model_name='household',
            name='budget_start_day',
            field=models.IntegerField(blank=True, help_text='매월 이 날짜를 가계부 주기의 시작일로 설정합니다. (예: 1이면 1일~말일, 25이면 25일~24일)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='가계부 주기 시작일'),
        ),
    ]
