# Generated by Django 6.0.3 on 2026-05-14 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0018_remove_historicalhousehold_default_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='선택 시 소분류가 되며, 비워두면 대분류가 됩니다.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='ledgers.category', verbose_name='상위 카테고리(대분류)'),
        ),
    ]
