# Generated by Django 6.0.3 on 2026-04-10 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('ledgers', '0008_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memos', to='ledgers.household'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('free', '자유'), ('tip', '꿀팁'), ('question', '질문'), ('memo', '개인 메모')], default='free', max_length=20),
        ),
    ]
