# Generated by Django 6.0.3 on 2026-04-30 00:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_remove_post_category_board_post_board_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': '게시판 (Board)', 'verbose_name_plural': '게시판 목록 (Boards)'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '댓글 (Comment)', 'verbose_name_plural': '댓글 목록 (Comments)'},
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'verbose_name': '댓글 반응 (Comment Reaction)', 'verbose_name_plural': '댓글 반응 목록 (Comment Reactions)'},
        ),
        migrations.AlterModelOptions(
            name='historicalboard',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 게시판 (Board)', 'verbose_name_plural': 'historical 게시판 목록 (Boards)'},
        ),
        migrations.AlterModelOptions(
            name='historicalpost',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 게시글 (Post)', 'verbose_name_plural': 'historical 게시글 목록 (Posts)'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시글 (Post)', 'verbose_name_plural': '게시글 목록 (Posts)'},
        ),
        migrations.AlterModelOptions(
            name='postmedia',
            options={'verbose_name': '게시글 첨부 미디어 (Post Media)', 'verbose_name_plural': '게시글 첨부 미디어 목록 (Post Media)'},
        ),
        migrations.AlterModelOptions(
            name='reaction',
            options={'verbose_name': '게시글 반응 (Post Reaction)', 'verbose_name_plural': '게시글 반응 목록 (Post Reactions)'},
        ),
        migrations.AddField(
            model_name='board',
            name='board_admins',
            field=models.ManyToManyField(blank=True, help_text='이 게시판의 익명 작성자를 볼 수 있고 다른 사람의 글을 삭제/수정할 수 있습니다.', related_name='administered_boards', to=settings.AUTH_USER_MODEL, verbose_name='게시판 관리자'),
        ),
        migrations.AddField(
            model_name='board',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 게시판 여부'),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='익명 게시판 여부'),
        ),
    ]
