# Generated by Django 6.0.3 on 2026-04-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_alter_board_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='list_style',
            field=models.CharField(choices=[('table', '게시판형 (테이블)'), ('webzine', '웹진형 (썸네일)')], default='table', help_text='게시판 목록을 보여줄 형태를 선택하세요.', max_length=20, verbose_name='목록 스타일'),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='list_style',
            field=models.CharField(choices=[('table', '게시판형 (테이블)'), ('webzine', '웹진형 (썸네일)')], default='table', help_text='게시판 목록을 보여줄 형태를 선택하세요.', max_length=20, verbose_name='목록 스타일'),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
    ]
